version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons:ro,Z
      - ./enterprise:/mnt/enterprise
      - ./odoo-brasil:/mnt/odoo-brasil
      - ./odoo/odoo:/usr/lib/python3/dist-packages/odoo
    command: odoo
    restart: always
    tty: true
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
  odoo: